encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path( "wiki/create_page/", views.create_page, name="create_page" ),
    path( "wiki/random_page/", views.random_page, name="random_page" ),
    path( "wiki/<str:title>/", views.entry, name="entry" ),
    path( "search/", views.search, name="search" ),
    path( "edit/", views.edit, name="edit" ),
    path( "save/", views.save_edit, name="save" ),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls",  namespace="encyclopedia"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from . import util

from markdown import markdown 

import logging
from click import secho
from django import forms
import random

class NewPage(forms.Form):
    title    = forms.CharField( label="title" ) # We are going to use the label to access the title
    textarea = forms.CharField( widget=forms.Textarea )

class Search(forms.Form):
    query = forms.CharField( label="query" )

def index(request):
    secho( "[DEBUG] --> CURRENTLY AT INDEX\n\n", fg="green" )
    return render(request, "encyclopedia/index.html", {
        "title"   : "Home",
        "heading" : "All Pages",
        "entries" : util.list_entries()
    })


def entry( request, title ):
    
    page = util.get_entry( title )
    
    if not page:
        return render( request, "encyclopedia/404.html" )
    
    return render( request, "encyclopedia/pages.html" , {
        "title" : title,
        "content" : markdown( page ),
    } )


def create_page( request ):
    if request.method == "GET":
        return render( request, "encyclopedia/create_page.html" )
    if request.method == "POST":
        secho( "<<<<<<<A post message was submitted>>>>>>>", fg="green" )
        new_page = request.POST
        
        if new_page:
            title    = new_page[ "title" ]
            textarea = new_page[ "content" ] 

            # DEBUG
            secho( f"Request has title -> { title }", fg="green" )
            secho( f"Request has body -> \n{ textarea }", fg="green" )
            
            for page in util.list_entries():
                if page.lower() == title.lower():
                    return render( request, "encyclopedia/page_exists.html" )
            
            util.save_entry( title,"# " + title + "\n" + textarea )
            return index(request) # Dunno if this makes sense
            
    return render( request, "encyclopedia/create_page.html", {
        "form" : NewPage(),
    } )


def search( request ):
    """
    This is for when the user submits a search
    """
    secho( "[DEBUG] --> search function triggered", fg="green" )
    if request.method == "POST":
        
        query = request.POST['q']

        if not query: return render( request, "encyclopedia/404.html" )

        q = query
        all_entries = util.list_entries()

        found = [ entry for entry in all_entries if q.lower() in entry.lower() ]
        secho(found, fg="yellow")
        if not found: 
            return render( request, "encyclopedia/pages.html", {
                "title"   : "Search",
                "content" : f"<h1> PAGE NOT FOUND </h1>\
                              <h3> {q.upper()} not available in this encyclopedia"
            } )

        if len(found) == 1 and q.lower() == found[0].lower():
            return render( request, "encyclopedia/search.html", {
                        "title"   : q,
                        "content" : markdown( util.get_entry( found[0] ) ),
                    })
        else:
            return render(request, "encyclopedia/index.html", {
                        "title"   : "Search",
                        "heading" : "Search Results:",
                        "entries" : found
                    })


def random_page( request ):
    
    page_to_render = random.choice( util.list_entries() )
    
    return render( request, "encyclopedia/pages.html", {
        "title"   : page_to_render,
        "content" : markdown( util.get_entry( page_to_render ) ),
        })

def edit( request ):
    
    if request.method == "POST":
        secho( request.POST['entry'], fg="yellow" )
        title = request.POST['entry']
        content = util.get_entry(title)
        return render( request, "encyclopedia/edit.html", {
            "page_title"   : title,
            "content" : content
        } )


def save_edit(request):
    
    if request.method == "POST":
        title = request.POST['page_title']
        content = request.POST['content']
        util.save_entry( title, content )

        return entry( request, title )

encyclopedia/templates/encyclopedia/create_page.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}

Create Your Own Page

{% endblock %}

{% block body %}

<div>
    <form action="{% url 'encyclopedia:create_page' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <!-- <input type="text" placeholder="Title?">
        <textarea name="description" id="txtarea"></textarea> -->
        <input type="submit">
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}

Edit Page

{% endblock %}

{% block body %}

<h1>Edit Page >> {{ title }}</h1>

<div>
    <form action="{% url 'encyclopedia:save' %}" method="post">
        {% csrf_token %}
        <!-- {{ form }} -->
        <label for="page_title">Title</label>
        <input type="text" value="{{ page_title }}" name="page_title" >
        <br>
        <label for="content">Markdown Content:</label>
        <br>
        <textarea name="content">{{ content }}</textarea>
        <br>
        <input type="submit" value="new_page", class="btn btn-primary">
    </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>
        {{ heading }}
    </h1>

    <ul>
    {% for entry in entries %}
        <li>
            <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
        </li>
    {% endfor %}
</ul>


{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" href="{% static 'encyclopedia/wiki-logo.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST" >
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_page' %}">
                        Create New Page
                    </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">
                        Random Page
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>

</html>

encyclopedia/templates/encyclopedia/page_exists.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="icon" href="{% static 'encyclopedia/wiki-logo.png' %}">
        <title>Not Found</title>
        <link rel="stylesheet" href="{% static 'encyclopedia/404page.css' %}">
    </head>

    <body>
        <div>
            <h1>Page Already Exists, Click Picture Below To Retry</h1>
        </div>
        <div>
            <a href="{% url 'encyclopedia:create_page' %}">
                <img src="{% static 'encyclopedia/404cat.jpg' %}" alt="404cat">
            </a>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/pages.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{ title | safe }}
{% endblock %}

{% block body %}

{{ content | safe }}

    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry" value="{{ title }}">
        <input type="submit" value="edit" class="btn btn-danger">
    </form>

{% endblock %}